version: '3.1'

services:
    nestdb_pg:
        image: postgres:latest
        container_name: nestdb_pg
        restart: always
        environment:
            POSTGRES_DB: nestdb
            POSTGRES_USER: user_nest
            POSTGRES_PASSWORD: secret1234
        volumes:
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./postgres:/var/lib/postgresql/data
        ports:
            - 5435:5432
