@baseURL = http://localhost:8000/api/projects
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQ1JFQVRPUiIsInN1YiI6IjdkNTYyYTlkLTYwZDktNDFlZi1hOWVkLTY4ZmYyMDg3ODIzYiIsImlhdCI6MTY3OTI2NzcxMCwiZXhwIjoxNjc5MjcxMzEwfQ.F1jtxEzhwRwSUyl87iEq7JSWR5cvMYRVuYm2BrhN2wM
@projectID = e3685c60-079a-493e-b30d-48adf83515ae
@userOwnerId = 7d562a9d-60d9-41ef-a9ed-68ff2087823b

###############################################################

POST {{baseURL}}/create/
Content-Type: application/json
Authorization: {{token}}

{
    "userOwnerId": "{{userOwnerId}}",
    "name": "Proyecto de prueba 2",
    "description": "Proyecto de prueba 2"
}

###############################################################

GET {{baseURL}}/all/

###############################################################

GET {{baseURL}}/{{projectID}}/
Authorization: {{token}}

###############################################################

PUT {{baseURL}}/edit/{{projectID}}/
Content-Type: application/json
Authorization: {{token}}

{
    "description": "Actualización del projecto"
}

###############################################################

DELETE {{baseURL}}/delete/{{projectID}}/

###############################################################
