@baseURL = http://localhost:8000/api/projects
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU4iLCJzdWIiOiI3ZDU2MmE5ZC02MGQ5LTQxZWYtYTllZC02OGZmMjA4NzgyM2IiLCJpYXQiOjE2Nzc4NzU4NDAsImV4cCI6MTY3Nzg3OTQ0MH0.LNroXGyX3ULFQnKcNjd8CCPJ9fCw0uEk3VEyb5E4vOA
@projectID = e3685c60-079a-493e-b30d-48adf83515ae

###############################################################

POST {{baseURL}}/register/
Content-Type: application/json

{
    "name": "Proyecto de prueba",
    "description": "Proyecto de prueba"
}

###############################################################

GET {{baseURL}}/all/

###############################################################

GET {{baseURL}}/{{projectID}}/
Authorization: {{token}}

###############################################################

PUT {{baseURL}}/edit/{{projectID}}/
Content-Type: application/json
Authorization: {{token}}

{
    "description": "Actualización del projecto"
}

###############################################################

DELETE {{baseURL}}/delete/{{projectID}}/

###############################################################
