@baseURL = http://localhost:8000/api/users
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQ1JFQVRPUiIsInN1YiI6IjdkNTYyYTlkLTYwZDktNDFlZi1hOWVkLTY4ZmYyMDg3ODIzYiIsImlhdCI6MTY3OTI2Mjc0MSwiZXhwIjoxNjc5MjY2MzQxfQ.sHjKvTj8LSZzOrtGBZaV5Cl3RbAVX6UiXmmSRGhekz8
@userID = 7d562a9d-60d9-41ef-a9ed-68ff2087823b

###############################################################

POST {{baseURL}}/register/
Content-Type: application/json
Authorization: {{token}}

{
    "firstName": "test",
    "lastName": "user",
    "age": 22,
    "email": "test.user@email.com",
    "username": "test_user",
    "password": "test_password",
    "role": "ADMIN"
}

###############################################################

GET {{baseURL}}/list/
Authorization: {{token}}

###############################################################

GET {{baseURL}}/list/{{userID}}/

###############################################################

PUT {{baseURL}}/edit/{{userID}}/
Content-Type: application/json
Authorization: {{token}}

{
    "firstName": "test update"
}

###############################################################

POST {{baseURL}}/register/
Content-Type: application/json
Authorization: {{token}}

{
    "firstName": "Delete",
    "lastName": "user",
    "age": 0,
    "email": "delete.user@email.com",
    "username": "delete_user",
    "password": "delete_password",
    "role": "BASIC"
}

###############################################################

@deleteUserID = 730edd77-ea15-4800-a1f5-a1f5e76bb190

###############################################################

DELETE {{baseURL}}/delete/{{deleteUserID}}/
Authorization: {{token}}

###############################################################

GET {{baseURL}}/rick-and-morty/

###############################################################