@baseURL = http://localhost:8000/api/users
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU4iLCJzdWIiOiI3ZDRhMzlmMy1iNzM4LTQzYWQtYTFhMC03MTRkNWQwZGEwMzUiLCJpYXQiOjE2NzczNzIwMDgsImV4cCI6MTY3NzM3NTYwOH0.xFpY1FFCgXNf44xKpXR87bVSsbdTpniMWjWVX4b-vQ0
@userID = 7d4a39f3-b738-43ad-a1a0-714d5d0da035

###############################################################

POST {{baseURL}}/register/
Content-Type: application/json
Authorization: {{token}}

{
    "firstName": "test",
    "lastName": "user",
    "age": 22,
    "email": "test.user@email.com",
    "username": "test_user",
    "password": "test_password",
    "role": "ADMIN"
}

###############################################################

GET {{baseURL}}/all/
Authorization: {{token}}

###############################################################

GET {{baseURL}}/{{userID}}/

###############################################################

PUT {{baseURL}}/edit/{{userID}}/
Content-Type: application/json
Authorization: {{token}}

{
    "firstName": "test update"
}

###############################################################

DELETE {{baseURL}}/delete/{{userID}}/
Authorization: {{token}}

###############################################################