POST http://localhost:8000/api/users/register/
Content-Type: application/json

{
    "firstName": "test",
    "lastName": "user",
    "age": 22,
    "email": "test.user@email.com",
    "username": "test_user",
    "password": "test_password",
    "role": "ADMIN"
}

###############################################################

GET http://localhost:8000/api/users/all/

###############################################################

GET http://localhost:8000/api/users/7d4a39f3-b738-43ad-a1a0-714d5d0da035/

###############################################################

PUT http://localhost:8000/api/users/edit/7d4a39f3-b738-43ad-a1a0-714d5d0da035/
Content-Type: application/json

{
    "firstName": "test update"
}

###############################################################

DELETE http://localhost:8000/api/users/delete/7d4a39f3-b738-43ad-a1a0-714d5d0da035/

###############################################################