POST http://localhost:8000/api/users/user-to-project/
Content-Type: application/json

{
    "user": "7d4a39f3-b738-43ad-a1a0-714d5d0da035",
    "project": "248d8d96-a9d1-46f0-b781-0dbbd92ff222",
    "accessLevel": 50 
}

############################################################################